name: Publish Bolts
on:
  push:
    branches:
      - main
jobs:
  create-archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x' 
      - name: Build index
        run: python bin/index_bolts.py
      - name: Create gh-pages
        run: |
          cd docs
          git init
          git config user.name dvberkel 
          git config user.email daan.van.berkel@alliander.com
          git add .
          git commit -m 'generate gh-pages'
          git remote add repo git@github.com:alliander-opensource/bolts.git
          git fetch repo
          git push --force repo master:gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
