name: Publish Bolts
on:
  push:
    branches:
      - main
jobs:
  create-archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x' 
      - name: Build index
        run: python bin/index_bolts.py
      - name: Create gh-pages
        run: |
          cd docs
          git init
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'generate gh-pages'
          git remote add repo https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/alliander-opensource/bolts.git
          git fetch repo
          git push --force repo master:gh-pages
